accounts/urls.py
from django.urls import path
from accounts.views import UserRegisterView, LoginView, EditUserProfile

app_name = 'accounts'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('settings/', EditUserProfile.as_view(), name='settings'),
]

bloggingApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about_us, name='about'),
    path('new/', views.new_post, name='new_post'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('bookmarks/', views.my_bookmarks, name='bookmarks'),
    path('search/', views.search, name='search'),
    path('category/<str:cat>/', views.category_view, name='category'),
    path('like/<int:post_id>/', views.like_view, name='like_post'),
    path('bookmark/<int:post_id>/', views.bookmark_view, name='bookmark_post'),
    path('<slug:profile>/', views.profile, name='profile'),
    path('<slug:author>/<slug:slug>/', views.detail_post, name='detail'),
    path('<slug:author>/<slug:slug>/', 
        include(
            [
                path('edit', views.edit_post, name='edit_post'),
                path('delete-confirm', views.delete_post, name='delete_post'),
                path('comment', views.comments, name='comment'),
            ]
        ),
    ),
]

core/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from bloggingApp.util import unique_slug_generator
from django.conf import settings
User = settings.AUTH_USER_MODEL

STATUS = [
    (0, 'draft'),
    (1, 'publish'),
]

class Category(models.Model):
    """Making category for blogs"""
    cat = models.CharField("Post's Category", max_length=125, unique=True, blank=True)

    class Meta:
        verbose_name_plural = "Categories"
    
    def __str__(self):
        return self.cat
    
    def save(self, *args, **kwargs):
        self.cat = self.cat.lower()
        return super().save(*args, **kwargs)


class Post(models.Model):
    """Model for Blog Post"""
    title = models.CharField(max_length=200)
    snippets = models.CharField(max_length=120)
    slug = models.SlugField(unique=True, max_length=200, null=False, help_text="Post unique url")
    body = models.TextField()
    created_on = models.DateTimeField('Date Published', auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, max_length=125, related_name='p_category')
    cover_image = models.ImageField(upload_to='images/post/', null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)
    bookmarks = models.ManyToManyField(User, related_name='bookmarks', blank=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        """It redirects to the detail page after an database entry"""
        return reverse('core:detail', args=[str(self.user.username), str(self.slug)])

@receiver(pre_save, sender=Post)
def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=200)
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_date']

    def __str__(self):
        return '%s commented by- %s' % (self.post.title, self.user)

core/forms.py
from django import forms
from core.models import Post, Comment
from core.models import Category


class NewPostForm(forms.ModelForm):
    """Form layout for writing a new post"""
    cover_image = forms.ImageField(widget=forms.FileInput())

    # Override the __init__ method
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Retrieve categories from the database and create choices list
        categories = Category.objects.all()
        category_choices = [(None, 'Select a category')] + \
            [(category.id, category.cat) for category in categories]

        # Update the choices for the category field
        self.fields['category'].widget.choices = category_choices

    class Meta:
        model = Post
        fields = ['title', 'snippets', 'body',
                  'status', 'cover_image', 'category']

        widgets = {
            'category': forms.Select(attrs={'class': 'form-control form-select text-capitalize'})
        }

        error_messages = {
            'slug': {
                'unique': "This URL already exists!",
                'required': 'The field cannot be empty'
            },
            'title': {
                'required': "Title can't be blanked!"
            }
        }


class EditPostForm(forms.ModelForm):
    """Form layout for writing a new post"""
    cover_image = forms.ImageField(
        required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))

    # Override the __init__ method
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Retrieve categories from the database and create choices list
        categories = Category.objects.all()
        category_choices = [(None, 'Select a category')] + \
            [(category.id, category.cat) for category in categories]

        # Update the choices for the category field
        self.fields['category'].widget.choices = category_choices

    class Meta:
        model = Post
        fields = ['title', 'snippets', 'body',
                  'status', 'category', 'cover_image']

        widgets = {
            'category': forms.Select(attrs={'class': 'form-control form-select text-capitalize'})
        }

        error_messages = {
            'slug': {
                'unique': "This url already exists!",
                'required': 'The field cannot be empty'
            },

            'title': {
                'required': "Title can't be blanked!"
            }
        }


class CommentForm(forms.ModelForm):
    """Form for making comment on the post by authenticated user"""
    class Meta:
        model = Comment
        fields = ['body']

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Count
from django.http import Http404
from django.urls import reverse
from core.models import Post, Category
from django.db.models import Q
from core.forms import NewPostForm, CommentForm, EditPostForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

User = get_user_model()


def index(request):
    """
    Display a list of posts on the homepage.

    Returns:
        HttpResponse: Rendered HTML response with a list of posts.
    """
    posts = Post.objects.filter(status=1).order_by('-created_on')
    cats = Category.objects.order_by('cat')
    context = {'cats': cats, 'posts': posts}
    return render(request, 'core/index.html', context)


def about_us(request):
    """
    Display the 'About Us' page.

    Returns:
        HttpResponse: Rendered HTML response for the 'About Us' page.
    """
    return render(request, 'core/about.html')


def detail_post(request, author, slug):
    """
    Display details of a specific post.

    Returns:
        HttpResponse: Rendered HTML response with details of the post.
    """
    post = get_object_or_404(Post, author__username=author, slug__iexact=slug)
    context = {'post': post}
    return render(request, 'core/detail.html', context)


def comments(request, author, slug):
    """
    Handle comments for a specific post.

    Returns:
        HttpResponse: Rendered HTML response with comments for the post.
    """
    post = get_object_or_404(Post, author__username=author, slug=slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect(reverse('core:detail', args=[post.author, post.slug]))
    else:
        form = CommentForm()
        context = {'form': form}
        return render(request, 'core/detail.html', context)


@login_required
def new_post(request):
    """
    Create a new post.

    Returns:
        HttpResponse: Rendered HTML response for creating a new post.
    """
    if request.method == 'POST':
        form = NewPostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(reverse('core:detail', args=[request.user.username, post.slug]))
        else:
            context = {'filledform': form, 'form': form}
            return render(request, 'core/newpost.html', context)
    else:
        form = NewPostForm()
        context = {'form': form}
        return render(request, 'core/newpost.html', context)


@login_required
def edit_post(request, author, slug):
    """
    Edit existing post.

    Returns:
        HttpResponse: Rendered HTML response for editing an existing post.
    """
    post = get_object_or_404(Post, author__username=author, slug=slug)

    # Ensure the logged-in user is the author of the post
    if author != request.user.username:
        raise Http404

    if request.method == 'POST':
        form = EditPostForm(request.POST, request.FILES or None, instance=post)
        if form.is_valid():
            form.save()
            return redirect(reverse('core:detail', args=[request.user.username, post.slug]))
    else:
        form = EditPostForm(instance=post)

    context = {'post': post, 'form': form}
    return render(request, 'core/edit.html', context)


@login_required
def delete_post(request, author, slug):
    """
    Delete a post from the database and media too.

    Returns:
        HttpResponse: Redirects to the user's dashboard after deleting the post.
    """
    post = get_object_or_404(Post, author__username=author, slug=slug)
    if request.user != post.author:
        raise Http404

    if request.method == 'POST':
        if post.cover_image:
            post.cover_image.delete()
        post.delete()
        return redirect(reverse('core:dashboard'))
        
    return redirect(reverse('core:dashboard'))


def search(request):
    """
    Search a post with a matching title.

    Returns:
        HttpResponse: Rendered HTML response with search results.
    """
    if request.method == 'GET':
        query = request.GET.get('q')

    search_posts = Post.objects.filter(
        Q(title__icontains=query) | Q(), status=1).order_by('-created_on')

    # search_user = User.objects.filter(Q(username__icontains=query) | Q(full_name__icontains=query))

    context = {
        'object_list': search_posts, 'query': query
    }
    return render(request, 'core/search.html', context)


def profile(request, profile):
    """
    Display user profile and associated posts.

    Returns:
        HttpResponse: Rendered HTML response with user profile and posts.
    """
    user_profile = get_object_or_404(User, username=profile)
    posts = Post.objects.filter(
        author__username=profile, status=1).order_by('-created_on')
    context = {'profile': user_profile, 'posts': posts}
    return render(request, 'core/profile.html', context)


@login_required
def dashboard(request):
    """
    Display the user's dashboard with their posts, likes, and comments.

    Returns:
        HttpResponse: Rendered HTML response with the user's dashboard information.
    """
    posts = Post.objects.filter(author=request.user).order_by('-created_on').annotate(
        total_likes=Count('likes', distinct=True),
        total_comments=Count('comments', distinct=True)
    )

    context = {
        'post_count': posts.count(),
        'posts': posts,
        'total_likes_received': sum(post.total_likes for post in posts),
        'total_comments_received': sum(post.total_comments for post in posts),
    }

    return render(request, 'core/dashboard.html', context)


@login_required
def my_bookmarks(request):
    """
    Display posts bookmarked by the logged-in user.

    Returns:
        HttpResponse: Rendered HTML response with bookmarked posts.
    """
    user_bookmarks = Post.objects.filter(bookmarks=request.user)
    return render(request, 'core/bookmarks.html', {'bookmarks': user_bookmarks})


@login_required
def like_view(request, post_id):
    """
    Handle the like/unlike action for a post.

    Parameters:
        request (HttpRequest): The HTTP request object.
        post_id (int): The ID of the post to be liked/unliked.

    Returns:
        JsonResponse: A JSON response containing the updated like count and whether the user has liked the post.

    Raises:
        Http404: If the post with the specified ID does not exist.
    """
    post = get_object_or_404(Post, id=post_id)

    if request.user in post.likes.all():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True

    like_count = post.likes.count()

    return JsonResponse({'like_count': like_count, 'is_liked': is_liked})


@login_required
def bookmark_view(request, post_id):
    """
    Handle the bookmark/unbookmark action for a post.

    Parameters:
        request (HttpRequest): The HTTP request object.
        post_id (int): The ID of the post to be liked/unliked.

    Returns:
        JsonResponse: A JSON response containing the updated bookmark count and whether the user has bookmared the post.

    Raises:
        Http404: If the post with the specified ID does not exist.
    """
    post = get_object_or_404(Post, id=post_id)
    
    if request.user in post.bookmarks.all():
        post.bookmarks.remove(request.user)
        is_bookmarked = False
    else:
        post.bookmarks.add(request.user)
        is_bookmarked = True
    bookmark_count = post.bookmarks.count()

    return JsonResponse({'bookmark_count': bookmark_count, 'is_bookmarked': is_bookmarked})


def category_view(request, cat):
    """
    Display posts of a specific category.

    Returns:
        HttpResponse: Rendered HTML response with posts of the specified category.
    """
    posts = Post.objects.filter(category__cat=cat.lower()).order_by('-created_on')
    return render(request, 'core/category.html', {'cat': cat, 'posts': posts})

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Font Awesome Free's Solid and Brand files -->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

    <!-- My css files -->
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/codehilite_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/style.css' %}">
    {% block styles %}{% endblock %}

    <!-- Title for every page -->
    <title>{% block title %}Code Blog{% endblock %}</title>
</head>

<body>
    <!-- Main nav -->
    <header class="main-header">
        <div class="header-container">
            <a href="{% url 'core:index' %}" class="main-logo">Code Blog</a>
            <div class="header-search">
                <form method="get" action="/search" autocomplete="off" class="search-form">
                    <div class="form-wrapper">
                        <input type="text" id="my-search" placeholder="Search..." name="q" onchange="searchEmpty()">
                        <button type="submit" class="search-but" id="searchButton" disabled="disabled">
                            <i class="fa-solid fa-magnifying-glass search-icon"></i>
                        </button>
                    </div>
                </form>
            </div>
            <div class="user-sec">
                {% if user.is_authenticated %}
                <div class="authentication-top-nav">
                    <a href="{% url 'core:new_post' %}" class="nav-new_post">Create Post</a>
                    <img src="{{ user.pfp.url }}" class="nav-user-img" id="dropbtn" onclick="toogleDropdown()">
                    <div class="dropdown-nav" id="dropdown">
                        <ul>
                            <li class="nav-userinfo">
                                <span>Singed in as</span><br>
                                <span class="bold">@{{ user.username }}</span>
                            </li>
                            <hr />
                            <li><a href="{% url 'core:dashboard' %}" class="drop-nav-item">Dashboard</a></li>
                            <li><a href="{% url 'core:profile' user.username %}" class="drop-nav-item">Your Profile</a>
                            </li>
                            <li><a href="{% url 'core:new_post' %}" class="drop-nav-item">Create Post</a></li>
                            <li><a href="{% url 'core:bookmarks' %}" class="drop-nav-item">Bookmarks</a></li>
                            <li><a href="{% url 'accounts:settings' %}" class="drop-nav-item">Settings</a></li>
                            <hr />
                            <li>
                                <form class="d-inline" action="{% url 'logout' %}" method="post">
                                    {% csrf_token %}
                                    <button class="drop-nav-item border-0" type="submit">Sign Out</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
                {% else %}
                <div class="authentication-top-nav">
                    <a href="{% url 'accounts:login' %}" class="top-nav-login">Login</a>
                    <a href="{% url 'accounts:register' %}" class="top-nav-create">Create account</a>
                </div>
                {% endif %}
            </div>
        </div>
    </header>

    <div class="body-wrapper">
        {% block body %}{% endblock %}
    </div>

    <script>
        // dropdown for user navigation.
        function toogleDropdown() {
            document.getElementById('dropdown').classList.toggle('dropdown-visibility')
        }
        window.onclick = function (event) {
            if (!event.target.matches('#dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-nav");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('dropdown-visibility')) {
                        openDropdown.classList.remove('dropdown-visibility');
                    }
                }
            }
        }

        // function to disable home page search bar when searchbar is empty.
        let searchButton = document.getElementById('searchButton')

        function searchEmpty() {
            searchButton.disabled = false
        }
    </script>
    {% block script %}{% endblock %}
</body>

</html>

templates/core/bookmarks.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
My Bookmarks - Code Blog
{% endblock %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/profile.css' %}">
{% endblock %}

{% block body %}
<div class="container-fluid p-0 d-flex flex-column align-items-center mt-7">
    <div class="profile-posts d-flex flex-column gap-3">
        <span class="h3 fw-bolder">My Bookmarks</span>
        {% for post in bookmarks %}
        <article class="profile-articles rounded d-flex flex-row">
            <div class="p-4">
                <div class="container d-flex gap-2">
                    <a href="{% url 'core:profile' post.author %}">
                        <img src="{{ post.author.pfp.url }}" class="article-author-img img-thumbnail object-fit-cover rounded-circle">
                    </a>
                    <div class="d-flex flex-column mb-3">
                        <a href="{% url 'core:profile' post.author %}" class="pu-name  text-decoration-none text-dark" style="">{{ post.author.full_name }}</a>
                        <small class="pu-time">Published - {{ post.created_on|naturaltime }}</small>
                    </div>
                </div>
                <div class="container article-wrapper mb-3">
                    <a href="{% url 'core:detail' post.author post.slug %}" class="text-decoration-none"><h2 class="m-0 p-0">{{ post.title }}</h2></a>
                </div>
                <div class="container snippets">
                    <span class="fs-6">{{ post.snippets }}</span>
                </div>
            </div>
            <div class="ms-auto bg-gray rounded">
                {% if post.cover_image %}
                <img src="{{ post.cover_image.url }}" class="p-post-img rounded" alt="post-image">
                {% endif %}
            </div>
        </article>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/core/category.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
{{ cat|title }} category - Code Blog
{% endblock %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/index.css' %}">
{% endblock %}

{% block body %}
<div class="grid-wrapper d-flex flex-row m-auto gap-1">
    <main class="container d-flex flex-column gap-2 main-block">
        <span class="latest-post-span fw-bolder w-auto py-2">Category - {{ cat|title }}</span>
        <div class="d-flex flex-column gap-5">
            {% for post in posts %}
            <article class="main-articles h-auto">
                <div class="post-img">
                    {% if post.cover_image %}
                    <img src="{{ post.cover_image.url }}">
                    {% endif %}
                </div>
                <div class="py-4 px-4 d-flex flex-column gap-2">
                    <a href="{% url 'core:category' post.category %}" class="fw-bolder text-decoration-none index-cate">{{ post.category|title }}</a>
                    <div class="d-flex flex-column align-items-start gap-0 text-decoration-none">
                        <a href="{% url 'core:profile' post.author %}"
                            class="flex-row author-info-link text-decoration-none">
                            <img src="{{ post.author.pfp.url }}" class="author-img" onclick="">
                            <span class="ms-2 fw-semibold">{{ post.author.full_name }}</span>
                        </a>
                        <p class="m-0 p-0 lh-1 ms-5">Published on - {{ post.created_on|date }}</p>
                    </div>
                    <div class="d-flex flex-column gap-2 post-info mx-5 mt-1">
                        <a href="{% url 'core:detail' post.author post.slug %}">
                            <h2 class="first-letter-capital">{{ post.title }}</h2>
                        </a>
                        <p class="post-snippet">{{ post.snippets }}</p>
                    </div>
                    <div class="d-flex gap-4 mx-5">
                        <div class="pointer">
                            <i class="fa-solid fa-heart me-2" style="color: #ff0000;"></i>
                            {{ post.likes.count }}
                        </div>
                        <div class="pointer">
                            <i class="fa-regular fa-comment me-2"></i>{{ post.comments.count }}
                            Comment{{post.comments.count | pluralize }}
                        </div>
                    </div>
                </div>
            </article>
            {% endfor %}
        </div>
    </main>
    <section class="container sidebar p-4">
        <div class="sidebar-nav">
            <span class="d-block text-bg-primary fw-bolder fs-5">Navigation</span>
            <div class="d-flex flex-column flex-nowrap gap-2 mt-3">
                <a href="{% url 'core:index' %}" class="block rounded-pill text-decoration-none px-4 py-1 fw-semibold">Home</a>
                <a href="{% url 'core:about' %}" class="block rounded-pill text-decoration-none px-4 py-1 fw-semibold">About</a>
                <a href="#" class="block rounded-pill text-decoration-none px-4 py-1 fw-semibold">Contact us</a>

            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/core/dashboard.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Dashboard - Code Blog{% endblock %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/dashboard.css' %}">
{% endblock %}

{% block body %}
<div class="container dashboard-wrapper">
    <div class="container dashboard-max-w">
        <h3>My Dashboard</h3>
        <div class="container row gap-4 mt-4">
            <div class="card col card-height">
                <div class="card-body text-center">
                    <h5 class="card-title">Post Published</h5>
                    <p class="card-text ">{{ post_count }}</p>
                </div>
            </div>
            <div class="card col card-height">
                <div class="card-body text-center">
                    <h5 class="card-title">Likes Gained</h5>
                    <p class="card-text">{{ total_likes_received }}</p>
                </div>
            </div>
            <div class="card col card-height">
                <div class="card-body text-center">
                    <h5 class="card-title">Comments Received</h5>
                    <p class="card-text">{{ total_comments_received }}</p>
                </div>
            </div>
        </div>
        <main class="container d-flex flex-column gap-2 mt-4">
            {% if posts %}
                {% for post in posts %}
                    <article
                        class="dash-article d-flex rounded gap-2 border border-2 justify-content-between align-items-center px-3 py-1">
                        <a href="{% url 'core:detail' post.author post.slug %}"
                            class="dash-p-title h-auto fw-bold w-50 text-decoration-none">{{ post.title }}</a>
                        <span class="dash-p-status px-2 py-1">
                            {% if post.status == 0 %}
                            Draft
                            {% else %}
                            Published
                            {% endif %}
                        </span>
                        <div class="dash-p-buttons">
                            <a class="text-decoration-none text-primary mx-2"
                                href="{% url 'core:edit_post' post.author post.slug %}">Edit</a>
                            <button class="btn btn-danger" data-toggle="modal" data-target="#deleteConfirmationModal{{ post.id }}">Delete</button>
                        </div>
                    </article>
                    
                    <!-- Delete Confirmation Modal -->
                    <div class="modal fade" id="deleteConfirmationModal{{ post.id }}" tabindex="-1" role="dialog"
                        aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="deleteConfirmationModalLabel">Delete Confirmation</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure you want to delete the post "{{ post.title }}"?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                    <form method="post" action="{% url 'core:delete_post' post.author post.slug %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </main>
    </div>
</div>
{% endblock %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
{% endblock %}